AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stat-lambda

Resources:
  StatLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StatLambda
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
